// Generated by scripts/build-study-support.mjs; edit the source modules.
/*
Adapted SM-2 calculation: SkillCoco
MIT License

Copyright (c) 2026 Gourav Shah (Initcron Systems Private Limited)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
(()=>{"use strict";
// SM-2 calculation adapted from SkillCoco (MIT); see THIRD_PARTY_NOTICES.md.
const DAY=86400000,ZONE="America/New_York",DONE_KEY="abvm-daily-practice:v1";
const dayFormatter=new Intl.DateTimeFormat("en-CA",{timeZone:ZONE,year:"numeric",month:"2-digit",day:"2-digit"});
const day=now=>dayFormatter.format(new Date(now));
function afterDays(now,days){
  const p=Object.fromEntries(dayFormatter.formatToParts(new Date(now)).map(x=>[x.type,x.value]));
  // Noon UTC is safely within the intended Eastern school date, including DST.
  return Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day)+days,12);
}
const esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const FALLBACK=Object.freeze({"two-step-word-problem":"Two-step problems","place-value":"Place value","compare-numbers":"Comparing numbers",time:"Time",measurement:"Measurement","data-interpretation":"Reading charts","addition-within-100":"Addition","subtraction-within-100":"Subtraction",inference:"Reading clues",theme:"Story lessons","text-evidence":"Finding evidence","author-purpose":"Why authors write","word-choice":"Word meanings","cause-effect":"Cause and effect"});
const finite=(value,fallback)=>Number.isFinite(Number(value))?Number(value):fallback;
function sm2(quality,repetitions=0,ease=2.5,interval=0){
  const q=Math.max(0,Math.min(5,Math.floor(finite(quality,0)))),r=Math.max(0,Math.floor(finite(repetitions,0))),e=Math.max(1.3,finite(ease,2.5)),i=Math.max(0,finite(interval,0));
  if(q<3)return{repetitions:0,ease:e,intervalDays:1};
  return{repetitions:r+1,ease:Math.max(1.3,e+.1-(5-q)*(.08+(5-q)*.02)),intervalDays:r===0?1:r===1?6:i*e};
}
function validReview(row,now){
  const r=row?.Review;
  return r&&r.version===1&&Number.isFinite(r.reviewedAt)&&r.reviewedAt>0&&r.reviewedAt<=now+60000&&Number.isFinite(r.dueAt)&&r.dueAt>=r.reviewedAt&&r.dueAt<=r.reviewedAt+31*DAY&&Number.isFinite(r.intervalDays)&&r.intervalDays>=1&&r.intervalDays<=30&&Number.isFinite(r.ease)&&r.ease>=1.3&&r.ease<=3.5&&Number.isInteger(r.repetitions)&&r.repetitions>=0&&r.repetitions<=100?r:null;
}
function schedule(row,{correct=false,independent=false,now=Date.now()}={}){
  if(!Number.isFinite(now)||now<=0)throw new Error("Review time must be valid");
  const prior=validReview(row,now),sameDay=prior&&day(prior.reviewedAt)===day(now);
  // Repeating a skill today must not extend its long-term interval.
  if(prior&&correct&&independent&&(sameDay||!isDue(row,now)))return{...prior};
  const next=sm2(correct&&independent?4:correct?2:1,prior?.repetitions,prior?.ease,prior?.intervalDays);
  const intervalDays=Math.max(1,Math.min(30,Math.round(next.intervalDays)));
  return{version:1,repetitions:Math.min(100,next.repetitions),ease:Math.min(3.5,next.ease),intervalDays,reviewedAt:now,dueAt:afterDays(now,intervalDays)};
}
function dueAt(row,now){
  const review=validReview(row,now);if(review)return review.dueAt;
  const last=Math.max(finite(row?.LastSeenAt,0),finite(row?.LastResolution?.resolvedAt,0));
  return last>0&&last<=now+60000?afterDays(last,1):null;
}
function isDue(row,now=Date.now()){
  const at=dueAt(row,now);return at!==null&&day(at)<=day(now);
}
function candidates(pack={}){
  const result=new Map(Object.entries(FALLBACK).map(([id,label])=>[id,{id,label}]));
  for(const skill of pack?.contentPipeline?.skills||[])if(typeof skill?.id==="string"&&skill.id.trim())result.set(skill.id,{id:skill.id,label:String(skill.label||skill.id)});
  return result;
}
function dueSkills(pack,learning={},now=Date.now()){
  return [...candidates(pack).values()].filter(s=>isDue(learning[s.id],now)).sort((a,b)=>dueAt(learning[a.id],now)-dueAt(learning[b.id],now)||a.id.localeCompare(b.id));
}
function completion(now=Date.now()){
  try{const r=JSON.parse(localStorage.getItem(DONE_KEY)||"null");return r?.day===day(now)&&Number.isFinite(r.completedAt)&&r.completedAt<=now+60000?r:null}catch{return null}
}
function complete(now=Date.now()){
  try{localStorage.setItem(DONE_KEY,JSON.stringify({day:day(now),completedAt:now}));return true}catch{return false}
}
function render({pack={},learning={},now=Date.now()}={}){
  const due=dueSkills(pack,learning,now),done=completion(now),count=due.length;
  const title=done?"Today’s practice is complete":"Let’s practice";
  const copy=done?"Nice work. Come back tomorrow, or keep exploring at your own pace. No timer.":count?count+' skill'+(count===1?' is':'s are')+' ready for another look. We’ll mix a short review with school skills. No timer.':"Eight questions. No timer.";
  return '<section class="daily-practice" aria-labelledby="daily-practice-title"><p class="daily-eyebrow">'+(done?'DONE FOR TODAY':'YOUR DAILY PRACTICE')+'</p><h2 id="daily-practice-title">'+title+'</h2><p>'+copy+'</p>'+(count&&!done?'<ul aria-label="Skills to revisit">'+due.slice(0,3).map(s=>'<li>'+esc(s.label)+'</li>').join('')+'</ul>':'')+'<button type="button" data-subject-practice="daily">'+(done?'Practice a little more':'Practice now')+'<span aria-hidden="true">›</span></button></section>';
}
window.ABVMStudyReview=Object.freeze({sm2,schedule,validReview,dueAt,isDue,dueSkills,complete,completion,render});
})();

(()=>{
"use strict";
const esc=s=>String(s??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "\'":"&#39;"}[c]));
const SUBJECT_PRACTICE=Object.freeze({
  math:{mode:"math",label:"Math Dash",focus:"Build number sense",notes:["Place value: 462 has 4 hundreds, 6 tens, and 2 ones. The 6 is worth 60.","Add by making a ten: 38 + 7 = 38 + 2 + 5 = 45.","Subtract in parts: 52 − 18 = 52 − 10 − 8 = 34. Check: 34 + 18 = 52.","Read a word problem twice. Decide what changes, then label your answer."],question:"A class has 24 pencils, gets 13 more, then uses 8. How many are left?",answer:"29 pencils. First 24 + 13 = 37. Then 37 − 8 = 29."},
  reading:{mode:"words",label:"Word Power",focus:"Find clues in the text",notes:["Tell who the passage is about and what happens first, next, and last.","Find the main idea: what are most of the sentences telling you?", "Use a detail from the passage to explain your answer."],question:"Mia put on boots and opened her umbrella before going outside. What is the weather probably like?",answer:"It is probably raining. The boots and umbrella are clues; the passage does not say it directly."},
  spelling:{mode:"words",label:"Word Power",focus:"Listen, build, and read",notes:["Compare cap and cape: final silent e changes the vowel sound.","Read play, played, and playing. The ending changes when the action happens.","Say a word slowly, write its sounds, then read it back in a sentence."],question:"Which word has the same long-a sound as cake: cap, rain, or cat?",answer:"Rain. Both rain and cake have the long-a sound, even though it is spelled differently."},
  sight:{mode:"words",label:"Word Power",focus:"Read words in a sentence",notes:["Practice: because, before, after, could, would, and should.","Read: Before we play, we should put our books away.","Say a new sentence using because. Explain why something happens."],question:"Fill the gap: I wore a coat ___ it was cold. Choose before, because, or after.",answer:"Because. It connects wearing the coat with the reason: it was cold."},
  vocabulary:{mode:"words",label:"Word Power",focus:"Use context clues",notes:["Look at the words around an unfamiliar word for clues to its meaning.","Compare words: tiny and small mean nearly the same thing; tiny and huge are opposites.","Try your meaning in the sentence to check that it makes sense."],question:"The puppy was drowsy. It yawned and curled up to sleep. What does drowsy mean?",answer:"Sleepy. Yawning and getting ready to sleep help you work out the meaning."},
  religion:{mode:"words",label:"Word Power",focus:"Reading practice while you wait",notes:["No current Religion notes are posted. Use this short reading activity to build comprehension.","Read: Leo saw a new child sitting alone. He invited her to join his game. Soon they were both smiling.","Retell the beginning, middle, and end. Use a detail to explain how the characters feel."],question:"What did Leo do that helped the new child feel welcome?",answer:"He invited her to join his game. Their smiles are a clue that they enjoyed playing together."}
});
function studyNotes(subject){
  return [...(Array.isArray(subject?.topics)?subject.topics:[]),...(Array.isArray(subject?.studyNotes)?subject.studyNotes:[])]
    .filter(n=>typeof n==="string"&&n.trim()).map(n=>n.trim());
}
function subjectPracticeHtml(key){
  const p=SUBJECT_PRACTICE[key]||SUBJECT_PRACTICE.reading;
  return '<div class="subject-practice"><p class="practice-origin">'+(key==="religion"?'Reading enrichment':'Grade 2 STAR-style practice')+'</p><h3>'+esc(p.focus)+'</h3><ul>'+p.notes.map(n=>'<li>'+esc(n)+'</li>').join("")+'</ul><div class="practice-example"><strong>Try it together</strong><p>'+esc(p.question)+'</p><details class="practice-answer"><summary>Show answer & explanation</summary><p>'+esc(p.answer)+'</p></details></div><button type="button" data-subject-practice="'+p.mode+'">Practice with '+p.label+' <span aria-hidden="true">›</span></button><p class="practice-source-note">Original skill practice, not a teacher assignment or an official STAR test item.</p></div>';
}
window.ABVMStudyPractice=Object.freeze({notes:studyNotes,html:subjectPracticeHtml});
})();

(()=>{const style=document.createElement("style");style.dataset.abvmStudy="true";style.textContent=".daily-practice{grid-column:1/-1;margin:0 0 14px;padding:20px;border:1px solid #cfdeed;border-radius:22px;background:#f0f6fc;color:#183652}.daily-practice .daily-eyebrow{margin:0 0 8px;color:#365e85;font-size:.7059rem;font-weight:750;letter-spacing:.08em}.daily-practice h2{margin:0;font-size:1.3529rem;line-height:1.2;letter-spacing:-.025em}.daily-practice>p:not(.daily-eyebrow){margin:10px 0 14px;font-size:.8824rem;line-height:1.5}.daily-practice ul{display:flex;flex-wrap:wrap;gap:7px;list-style:none;padding:0;margin:0 0 16px}.daily-practice li{max-width:100%;padding:5px 9px;background:#fff;border-radius:9px;font-size:.7647rem;overflow-wrap:anywhere}.daily-practice button{display:flex;align-items:center;justify-content:space-between;gap:12px;width:100%;min-height:50px;padding:12px 16px;border:0;border-radius:14px;background:#123e68;color:#fff;font:inherit;font-weight:650;text-align:left}.daily-practice button:disabled{opacity:.7}.daily-practice small{display:block;margin-top:11px;color:#506273;font-size:.7059rem;line-height:1.5}.study-screen>.study-games-cta{padding:12px 16px;border-radius:16px;margin-bottom:18px}.study-screen>.study-games-cta>span,.study-screen>.study-games-cta small,.study-screen>.study-games-cta p{display:none}.study-screen>.study-games-cta{grid-template-columns:1fr auto;min-height:52px}.study-screen>.study-games-cta strong{font-size:.8824rem}\n";document.head.append(style)})();
