import fs from "node:fs";
import path from "node:path";
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),"utf8");
const exists=p=>fs.existsSync(path.join(root,p));
const fail=m=>{throw new Error(m)};
const pack=JSON.parse(read("pages/data/study-pack.json"));
const manifest=JSON.parse(read("pages/manifest.webmanifest"));
if(!pack?.pack?.sourceSufficient)fail("study-pack.json must contain a source-sufficient pack");
for(const key of ["importantDates","homework","subjects","reminders","parentNotices"])if(!Array.isArray(pack.pack[key]))fail("Missing pack array: "+key);
if(manifest.display!=="standalone")fail("PWA manifest must remain standalone");
const index=read("pages/index.html"),css=read("pages/styles.css"),app=read("pages/app.js"),sw=read("pages/sw.js");
if(!/href="\.\/styles\.css(?:\?[^"]*)?"/.test(index))fail("Gold-standard styles.css must be loaded");
if(!/src="\.\/app\.js(?:\?[^"]*)?"/.test(index))fail("Gold-standard app.js must be loaded");
for(const marker of ["YOUR SCHOOL PLAN","SCHOOL MONTH AT A GLANCE","SMALL STEPS, CALM PRACTICE","Family dashboard"])if(!app.includes(marker))fail("Missing historical UI marker: "+marker);
for(const marker of [".app-header",".day-picker",".calendar-card",".study-intro",".family-hero",".bottom-nav"])if(!css.includes(marker))fail("Missing historical style marker: "+marker);
if(!app.includes("./assets/abvm-app-icon-192.png"))fail("School seal must use local app asset");
for(const ref of ["pages/assets/abvm-app-icon-180.png","pages/assets/abvm-app-icon-192.png","pages/data/study-pack.json","pages/styles.css","pages/app.js"])if(!exists(ref))fail("Missing rollback asset: "+ref);
const swShell=[...sw.matchAll(/"\.\/([^"]+)"/g)].map(m=>m[1]).filter(Boolean);
for(const ref of swShell)if(!exists("pages/"+ref)&&ref!=="")fail("Service worker shell references missing file: "+ref);
console.log("Gold-standard rollback validation passed",{importantDates:pack.pack.importantDates.length,homework:pack.pack.homework.length});
